services:
    
    config.loader.dbbacked:
        class: Baikal\CoreBundle\Services\ConfigLoader\DbBackedConfigLoaderService
        arguments:
            - @doctrine.orm.entity_manager
            - "Baikal\ModelBundle\Entity\ConfigContainer"

    config.main:
        class: Baikal\CoreBundle\Services\MainConfigService
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [ "initialize", [ "@=service('config.loader.dbbacked').load('main')" ] ]