services:
    baikal_frontend.access_denied_handler:
        class: Baikal\FrontendBundle\Service\AccessDeniedHandler
        arguments:
            - @http_kernel
            - @security.context
            - @router
        tags:
            - { name: kernel.event_listener, event: security.kernel_response, method: handle }

